### ISSUE TITLE
 [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Leeebaba** [FFR66/Nacos_Rce#1]
![image](https://github.com/user-attachments/assets/e23f9e8c-0fe7-46e9-99f9-525a7a66de07)

**Comment by WingBy-Fkalis** [comment]
师傅开着代理吗，把全局代理关了

**Comment by Leeebaba** [comment]
是滴，我靠师傅您太迅速了，还有请教一下是有可能会碰撞不出来吗

**Comment by WingBy-Fkalis** [comment]
有可能，可能时间会特别的久
