### ISSUE TITLE
vps上没有请求记录

### ISSUE THREAD

**Issue by Qianxingyue** [FFR66/Nacos_Rce#4]
按照默认配置布置后，运行Nacos_Rce.py的时候，远端服务器没有产生任何访问记录。但是用telnet连通是会产生记录。

   / | / /___ __________  _____     / __ \________      / __ \____/ /___ ___  __
  /  |/ / __ `/ ___/ __ \/ ___/    / /_/ / ___/ _ \    / / / / __  / __ `/ / / /
 / /|  / /_/ / /__/ /_/ (__  )    / _, _/ /__/  __/   / /_/ / /_/ / /_/ / /_/ /
/_/ |_/\__,_/\___/\____/____/____/_/ |_|\___/\___/____\____/\__,_/\__,_/\__, /
                           /_____/              /_____/                /____/

        人外有人，天外有天
        [39m[31m                                       --By fkalis
          [39m
正在进行碰撞,请耐心等待!!
{'timestamp': '2024-07-17T17:14:36.050+08:00', 'status': 403, 'error': 'Forbidden', 'message': 'unknown user!', 'path': '/nacos/v1/cs/ops/data/removal'}
{'timestamp': '2024-07-17T17:14:36.081+08:00', 'status': 403, 'error': 'Forbidden', 'message': 'unknown user!', 'path': '/nacos/v1/cs/ops/data/removal'}
{'timestamp': '2024-07-17T17:14:36.112+08:00', 'status': 403, 'error': 'Forbidden', 'message': 'unknown user!', 'path': '/nacos/v1/cs/ops/data/removal'}
{'timestamp': '2024-07-17T17:14:36.143+08:00', 'status': 403, 'error': 'Forbidden', 'message': 'unknown user!', 'path': '/nacos/v1/cs/ops/data/removal'}
......

跑起来的时候只有这个removal路径的记录，感觉是完全没有和vps连通。
有没有同样情况的，捣鼓了一整天没有搞明白是为什么

**Comment by WingBy-Fkalis** [comment]
这个403表明漏洞不存在，因为之前复测的时候使用的客户端返回的是code关键词表示状态，这里是stuate导致没有匹配上，这个表明没有权限，漏洞不存在，除非可以登录

**Comment by Qianxingyue** [comment]
好快的回复！礼貌问一下这样没有/nacos/v1/cs/ops/derby这个路径的回显提示是正常的么 还是说是我运行得时间太短了

**Comment by WingBy-Fkalis** [comment]
没明白是什么意思，能出示一下截图吗师傅

**Comment by Qianxingyue** [comment]
非常抱歉，内网做了限制没法发图QAQ，但是我已经明白你第一条回复的意思了，非常感谢！
